
name: Release

on:
  push:
    branches: [ "main" ]


jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: docker build . -t goyaladit/nest-app2
    - run: echo "${{ secrets.DOCKER_PASSWORD}}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - run: docker push goyaladit/nest-app2
   